---

include:
  - project: 'saltbox/ci-lib'
    file: 'build-image.yml'
  - project: 'saltbox/ci-lib'
    file: 'mirror-image.yml'
  - project: 'saltbox/ci-lib'
    file: 'def-branch-merge-guard.yml'


Build Redis image:
  extends: .build-image
  variables:
    REGISTRY_ADDITIONAL_PATH: '/redis'
    CONTEXT_PATH: 'redis/'


Build OPA image:
  extends: .build-image
  variables:
    REGISTRY_ADDITIONAL_PATH: '/opa'
    CONTEXT_PATH: 'opa/'


Build SSHFS image:
  extends: .build-image
  variables:
    REGISTRY_ADDITIONAL_PATH: '/sshfs'
    CONTEXT_PATH: 'sshfs/'


Build make-certs image:
  extends: .build-image
  variables:
    REGISTRY_ADDITIONAL_PATH: '/make-certs'
    CONTEXT_PATH: 'make-certs/'


Build MongoDB image:
  extends: .build-image
  variables:
    REGISTRY_ADDITIONAL_PATH: '/mongodb'
    CONTEXT_PATH: 'mongodb/'


Build RabbitMQ image:
  extends: .build-image
  variables:
    REGISTRY_ADDITIONAL_PATH: '/rabbitmq'
    CONTEXT_PATH: 'rabbitmq/'


Build Keycloak image:
  extends: .build-image
  variables:
    REGISTRY_ADDITIONAL_PATH: '/keycloak'
    CONTEXT_PATH: 'keycloak/'
    TARGET: keycloak


Mirror Postgres image:
  extends: .mirror-image
  variables:
    SOURCE_IMAGE: 'postgres:16-alpine'
    REGISTRY_ADDITIONAL_PATH: '/postgres-16-alpine'


Trigger Proxy build:
  trigger:
    include:
      - local: 'proxy/.gitlab-ci.yml'
    strategy: depend
  rules:
    - changes:
        - 'nginx/**/*'
        - 'proxy/**/*'
