---

include:
  - project: 'saltbox/ci-lib'
    file: 'build-image.yml'
  - project: 'saltbox/ci-lib'
    file: 'def-branch-merge-guard.yml'
    rules:
      - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        when: never
      - when: always


.build-redis-image:
  extends: .build-image
  variables:
    REGISTRY_ADDITIONAL_PATH: '/redis'
    CONTEXT_PATH: 'redis/'


.opa:
  extends: .build-image
  variables:
    REGISTRY_ADDITIONAL_PATH: '/opa'
    CONTEXT_PATH: 'opa/'


.sshfs:
  extends: .build-image
  variables:
    REGISTRY_ADDITIONAL_PATH: '/sshfs'
    CONTEXT_PATH: 'sshfs/'


.make-certs:
  extends: .build-image
  variables:
    REGISTRY_ADDITIONAL_PATH: '/make-certs'
    CONTEXT_PATH: 'make-certs/'


.mongodb:
  extends: .build-image
  variables:
    REGISTRY_ADDITIONAL_PATH: '/mongodb'
    CONTEXT_PATH: 'mongodb/'

.rabbitmq:
  extends: .build-image
  variables:
    REGISTRY_ADDITIONAL_PATH: '/rabbitmq'
    CONTEXT_PATH: 'rabbitmq/'

Build Redis image for tag:
  extends: .build-redis-image
  variables:
    IMAGE_TAG: '$CI_COMMIT_TAG'
  rules:
    - if: '$CI_COMMIT_TAG'


Build Redis image for branch:
  extends: .build-redis-image
  variables:
    IMAGE_TAG: '$CI_COMMIT_BRANCH'
  rules:
    - if: '$CI_COMMIT_BRANCH'


Trigger Proxy build:
  trigger:
    include: 
    - local: 'proxy/.gitlab-ci.yml'
  rules:
    - changes:
        - 'nginx/**/*'
        - 'proxy/**/*'


Trigger Keycloak build:
  trigger:
    include:
      - local: 'keycloak/.gitlab-ci.yml'
  rules:
    - changes:
        - 'keycloak/**/*'


Build OPA image for tag:
  extends: .opa
  variables:
    IMAGE_TAG: '$CI_COMMIT_TAG'
  rules:
    - if: '$CI_COMMIT_TAG'


Build OPA image for branch:
  extends: .opa
  variables:
    IMAGE_TAG: '$CI_COMMIT_BRANCH'
  rules:
    - if: '$CI_COMMIT_BRANCH'


Build SSHFS image for tag:
  extends: .sshfs
  variables:
    IMAGE_TAG: '$CI_COMMIT_TAG'
  rules:
    - if: '$CI_COMMIT_TAG'


Build SSHFS image for branch:
  extends: .sshfs
  variables:
    IMAGE_TAG: '$CI_COMMIT_BRANCH'
  rules:
    - if: '$CI_COMMIT_BRANCH'


Build make-certs image for tag:
  extends: .make-certs
  variables:
    IMAGE_TAG: '$CI_COMMIT_TAG'
  rules:
    - if: '$CI_COMMIT_TAG'


Build make-certs image for branch:
  extends: .make-certs
  variables:
    IMAGE_TAG: '$CI_COMMIT_BRANCH'
  rules:
    - if: '$CI_COMMIT_BRANCH'


Build MongoDB image for tag:
  extends: .mongodb
  variables:
    IMAGE_TAG: '$CI_COMMIT_TAG'
  rules:
    - if: '$CI_COMMIT_TAG'


Build MongoDB image for branch:
  extends: .mongodb
  variables:
    IMAGE_TAG: '$CI_COMMIT_BRANCH'
  rules:
    - if: '$CI_COMMIT_BRANCH'

Build RabbitMQ image for tag:
  extends: .rabbitmq
  variables:
    IMAGE_TAG: '$CI_COMMIT_TAG'
  rules:
    - if: '$CI_COMMIT_TAG'

Build RabbitMQ image for branch:
  extends: .rabbitmq
  variables:
    IMAGE_TAG: '$CI_COMMIT_BRANCH'
  rules:
    - if: '$CI_COMMIT_BRANCH'
