---

services:
  keycloak:
    build:
      context: keycloak
      target: keycloak
      args:
        BASE_KEYCLOAK_IMG: "${IMAGE_REGISTRY}/salt.box/salt-box-compose/keycloak-base:master"
        KC_HTTP_RELATIVE_PATH: ${KEYCLOAK_BASE_URL}
    develop:
      watch:
        - action: rebuild
          path: keycloak/
    image: 'keycloak:custom'

  keycloak-init:
    build:
      context: keycloak
      target: keycloak-init
      args:
        BASE_KEYCLOAK_IMG: "${IMAGE_REGISTRY}/salt.box/salt-box-compose/keycloak-base:master"
        KC_HTTP_RELATIVE_PATH: ${KEYCLOAK_BASE_URL}
    develop:
      watch:
        - action: rebuild
          path: keycloak/
    image: 'keycloak-init:custom'
