services:
  nginx:
    image: nginx:latest
    container_name: fastms-proxy-nginx
    env_file:
      - .env
    environment:
      BACKEND_HTTP_PORT: '${BACKEND_HTTP_PORT}'
      KEYKOACK_BASE_URL: ${KEYKOACK_BASE_URL}
    develop:
      watch:
        - action: rebuild
          path: nginx-proxy/
    volumes:
      - './nginx-proxy:/etc/nginx/conf.d'
    ports:
      - 80:80
    depends_on:
      - fastms-core
      - fastms-frontend
      - keycloak
    networks:
      - default
      - fastms-local

  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: fastms-keycloak
    command: start --optimized
    env_file:
      - .env
    environment:
      KC_HOSTNAME: 'http://${KEYCLOACK_HOST}${KEYKOACK_BASE_URL}'
      KC_LOG_LEVEL: info
      KC_HTTP_ENABLED: true
      HTTP_ADDRESS_FORWARDING: true
    expose:
        - 8080
    networks:
      - fastms-local
  
  salt-master:
    build:
      context: salt/
      target: salt-master
    image: fastms-salt-master
    init: true
    container_name: fastms-salt-master
    ports:
      - '4505-4506:4505-4506'
    volumes:
      - 'salt_master_pki:/etc/salt/pki/'
    depends_on:
      - redis-salt

  redis-salt:
    image: redis:7.2-alpine
    container_name: fastms-redis-salt
    command:
      - --save 60 1
    volumes:
      - 'redis_salt_data:/data/'
    networks:
      - fastms-local
  
  fastms-core:
    build:
      context: fastms-core/
    container_name: fastms-core
    env_file:
      - .env
    environment:
      SALT_URL: 'https://fastms-salt-master:8000'
      REDIS_URL: 'redis://fastms-redis-salt:6379/0'
    expose:
      - ${BACKEND_HTTP_PORT}
    restart: no
    depends_on:
      - mongo
    networks:
      - fastms-local
  
  fastms-frontend:
    build:
      context: fastms-frontend/
      args:
        VITE_API_URL_HTTP: 'http://${SERVER_NAME}${BACKEND_BASE_URL}'
        VITE_API_URL_WS: 'ws://${SERVER_NAME}${BACKEND_BASE_URL}'
    develop:
      watch:
        - action: rebuild
          path: fastms-frontend/
    container_name: fastms-frontend
    env_file:
      - .env
    expose:
      - ${FRONTEND_HTTP_PORT}
    networks:
      - fastms-local
  
  mongo:
    image: mongo:7
    command: --quiet
    environment:
      # TODO Generate
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - fastms-local

volumes:
  salt_master_pki: {}
  redis_salt_data: {}

networks:
  default:
  fastms-local:
