services:
  proxy:
    environment:
      API_BASE_URL: '${WEB_SERVER_SCHEME}://${WEB_SERVER_HOST}${BACKEND_BASE_URL}'
      WS_SERVER_URL: '${WEB_SERVER_WS_SCHEME}://${WEB_SERVER_HOST}${BACKEND_BASE_URL}'
      OPEN_ID_AUTHORITY: '${WEB_SERVER_SCHEME}://${WEB_SERVER_HOST}${KEYCLOAK_BASE_URL}/realms/${KEYCLOAK_REALM}'
  keycloak:
    environment:
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
