x-default-service: &default
  restart: 'on-failure'
  stop_grace_period: ${STOP_GRACE_PERIOD}

services:
  sshfs-file-manager:
    <<: *default
    pull_policy: never
    build:
      context: ./sshfs_file_manager
    image: '${LOCAL_IMAGE_NAMESPACE}/sshfs_file_manager:${SSHFS_IMAGE_TAG}'
    extra_hosts: [ "localhost:host-gateway" ]
    user: '0'
    environment:
      BASIC_AUTH_PASSWORD: '${BASIC_AUTH_PASSWORD:-}'
      BASIC_AUTH_USERNAME: '${BASIC_AUTH_USERNAME:-}'
      FILEBROWSER_CONFIG: 'data/config.yaml'
      # FIXME (a.karmanov): That is broken for most cases
      ISSUER_URL: 'https://${WEB_SERVER_OUTER_SOCKET}${KEYCLOAK_BASE_URL}/realms/${KEYCLOAK_REALM}'
      KEYCLOAK_CLIENT: '${KEYCLOAK_CLIENT}'
      MIGRATION_SOURCE_ENABLED: '${SSHFS_FILE_MANAGER_MIGRATOR_SOURCE_ENABLED:-false}'
    volumes:
      - 'sshfs_file_manager_db:/home/filebrowser'
      - '${SALT_MASTER_STORAGE_PATH}:/srv/salt'
      - '${SSHFS_STORAGE_PATH}:/srv/sshfs'
      - '${SSHFS_MIGRATION_PATH}:/srv/migrator'
      - 'salt_repos:/srv/saltbox_salt'
    secrets:
      - keycloak_client_saltbox_core_password
    depends_on:
      keycloak-init:
        condition: service_completed_successfully
        restart: false
      saltbox-core-init:
        condition: service_completed_successfully
        restart: false

  keycloak-init:
    environment:
      SSHFS_MANAGER_ENABLED: true

  proxy:
    volumes:
      - ./proxy/includes/sshfs-file-manager.enabled.conf:/etc/nginx/includes/sshfs-file-manager.conf:ro

volumes:
  sshfs_file_manager_db:
    external: false
