---

## Salt.Box Compose frontend override file for dev-mode.

services:
  salt-box-frontend:
    build:
      context: $FRONTEND_BUILD_DIR
    image: 'saltbox-frontend:dev'
    develop:
      watch:
        - action: rebuild
          path: $FRONTEND_BUILD_DIR
  proxy:
    depends_on: !reset []
