---

## salt.box compose Keycloak override file for dev-mode.
##
## autotests one-shot service requires direct access to Keycloak API.
## It will be setted, if the Keycloak realm is not created yet. Also it can be
## setted manually.

x-default-service: &default
  restart: 'on-failure'
  stop_grace_period: ${STOP_GRACE_PERIOD}

services:
  keycloak-init:
    environment:
      KEYCLOAK_CLIENT_DIRECT_ACCESS: 'true'

  autotests:
    <<: *default
    profiles:
      - test
    image: '${IMAGE_REGISTRY}/salt-box-core/autotests:${CORE_AUTOTESTS_TAG}'
    pull_policy: always
    restart: 'no'
    command:
      - '--color=yes'
    environment:
      RESOURCE_URL: 'http://proxy/${BACKEND_PATH}'
      RESOURCE_WS_URL: 'ws://proxy/${BACKEND_PATH}'
      LOGGING: 'True'
      REDIS_HOST: redis-salt
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_USERNAME: '${REDIS_SALT_USERNAME}'
      REDIS_PASSWORD_FILE: '/run/secrets/redis_salt_password'
      USER_NAME: '${KEYCLOAK_USER_NAME}'
      USER_PASSWORD_FILE: '/run/secrets/keycloak_user_password'
      CLIENT_SECRET_FILE: '/run/secrets/keycloak_client_salt_box_core_password'
      GET_TOKEN_ENDPOINT: 'http://proxy/${KEYCLOAK_BASE_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token'
    secrets:
      - redis_salt_password
      - keycloak_user_password
      - keycloak_client_salt_box_core_password
    depends_on:
      proxy:
        condition: service_started
        restart: false
      keycloak:
        condition: service_healthy
        restart: false
      keycloak-init:
        condition: service_completed_successfully
        restart: false
      redis-salt:
        condition: service_started
        restart: false
      salt-box-core:
        condition: service_started
        restart: false
