services:
  salt-master:
    ports:
      - '4505-4506:4505-4506'
      - '8001:8000'
    develop:
      watch:
        - action: rebuild
          path: salt/
  fastms-core:
    develop:
      watch:
        - action: rebuild
          path: fastms-core/
  redis:
    ports:
      - '6379:6379'
  salt-minion:
    build:
      context: salt/
      target: salt-minion
    init: true
    develop:
      watch:
        - action: rebuild
          path: salt/
    deploy:
      mode: replicated
      replicas: ${MINION_REPLICAS:-1}
