---

## salt.box compose backend override file for dev-mode.

x-redis-based: &redis
  build:
    context: redis/
  image: 'redis-salt-box:dev'

services:
  keycloak-init:
    environment:
      KEYCLOAK_CLIENT_DIRECT_ACCESS: 'true'

  salt-box-core: &core
    build:
      context: $CORE_BUILD_DIR
      target: dev
    environment:
      - DEBUG=True
    tty: true  # colorize logs
    image: 'salt-box-core:dev'
    volumes:
      - '${CORE_BUILD_DIR}:/mnt/salt_box_core'

  salt-box-core-faststream-redis:
    <<: *core

  salt-box-core-tasks-watcher:
    <<: *core

  salt-box-core-taskiq-worker:
    <<: *core

  salt-box-core-taskiq-scheduler:
    <<: *core

  redis-salt:
    <<: *redis

  redis-taskiq:
    <<: *redis
    ports:
      - 6380:6379

  rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672
    # environment:
    #   - RABBITMQ_DEFAULT_USER=guest
    #   - RABBITMQ_DEFAULT_PASS=guest
    # volumes:
    #   - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    #   - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro

  opa:
    image: openpolicyagent/opa:latest-istio-static
    volumes:
      - './opa/policies:/policies'
