---

services:
  keycloak:
    build:
      context: keycloak
      target: keycloak
      args:
        KC_HTTP_RELATIVE_PATH: ${KEYCLOAK_BASE_URL}
    image: '${LOCAL_IMAGE_NAMESPACE}/keycloak:dev'

  keycloak-init:
    build:
      context: '${KEYCLOAK_INIT_DIR}'
      dockerfile: 'Dockerfile'
      target: dev
    image: 'saltbox-keycloak-init:dev'
    pull_policy: never
    develop:
      watch:
        - action: rebuild
          path: '${KEYCLOAK_INIT_DIR}/saltbox_keycloak_init'
          ignore:
            - '**/__pycache__/'
            - '**/*.pyc'
            - '**/*.egg-info/'
        - action: rebuild
          path: '${KEYCLOAK_INIT_DIR}/pyproject.toml'
