# Copyright 2025 Alexey Baikov, Anton Karmanov, Evgeny Berdnikov, Ivan Moshkov

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


x-default-service: &default
  restart: 'always'
  stop_grace_period: '${STOP_GRACE_PERIOD}'
  ulimits:
    nofile:
      soft: 65535
      hard: 65535
  logging:
    driver: 'json-file'
    options:
      max-size: '100m'
      max-file: 10

x-mongo-default-service: &mongo-default
  <<: *default
  image: '${IMAGE_REGISTRY}/saltbox-compose/mongodb:${MONGODB_IMAGE_TAG}'
  command: ['--quiet']
  secrets:
    - mongo_key_file
    - mongo_root_password
    - mongo_user_password
    - mongo_exporter_password

x-core-taskiq-depends: &core-taskiq-depends
  redis-taskiq:
    condition: service_started
    restart: false
  saltbox-core-init:
    condition: service_completed_successfully
    restart: false

services:
  proxy:
    <<: *default
    image: '${IMAGE_REGISTRY}/saltbox-compose/proxy:${PROXY_IMAGE_TAG}'
    environment:
      API_BASE_URL: 'https://${WEB_SERVER_OUTER_SOCKET}${GATEWAY_PATH}'
      BACKEND_HOSTNAME: saltbox-core
      BACKEND_HTTP_PORT: '${CORE_PORT}'
      BACKEND_PATH: '${BACKEND_PATH}'
      GATEWAY_HTTP_PORT: '${GATEWAY_HTTP_PORT}'
      GATEWAY_PATH: '${GATEWAY_PATH}'
      KEYCLOAK_BASE_URL: '${KEYCLOAK_BASE_URL}'
      NGINX_WORKER_CPU_AFFINITY: '${WEB_SERVER_WORKER_CPU_AFFINITY}'
      NGINX_WORKER_PROCESSES: '${WEB_SERVER_WORKER_PROCESSES}'
      OPEN_ID_AUTHORITY: 'https://${WEB_SERVER_OUTER_SOCKET}${KEYCLOAK_BASE_URL}/realms/${KEYCLOAK_REALM}'
      OPEN_ID_CLIENT_ID: '${KEYCLOAK_CLIENT}'
      OPEN_ID_REDIRECT_URL: 'https://${WEB_SERVER_OUTER_SOCKET}'
      SALTBOX_INCLUDES_DIR: '${WEB_SERVER_SALTBOX_INCLUDES_DIR}'
      WS_SERVER_URL: 'wss://${WEB_SERVER_OUTER_SOCKET}${BACKEND_PATH}'
    ports:
      - '${WEB_SERVER_PORT}:443'
    volumes:
      - 'proxy_certs:/etc/nginx/ssl/'
    secrets:
      - keycloak_client_saltbox_core_password

  keycloak-db:
    <<: *default
    image: '${IMAGE_REGISTRY}/saltbox-compose/postgres-16-alpine:${POSTGRES_IMAGE_TAG}'
    volumes:
      - 'keycloak-db_data:/var/lib/postgresql/data/'
    environment:
      POSTGRES_DB: ${KEYCLOAK_DATABASE}
      POSTGRES_PASSWORD_FILE: /run/secrets/keycloak_database_password
      POSTGRES_USER: ${KEYCLOAK_DATABASE_USER}
    healthcheck:
      test:
        - CMD-SHELL
        - su
        - postgres
        - '-c'
        - pg_isready
        - '--username'
        - '{KEYCLOAK_DATABASE_USER}'
        - '--dbname'
        - '${KEYCLOAK_DATABASE}'
      interval: '5s'
      retries: 5
      start_period: '10s'
    secrets:
      - keycloak_database_password
    expose:
      - '${KEYCLOAK_DB_PORT}'

  keycloak:
    <<: *default
    image: '${IMAGE_REGISTRY}/saltbox-compose/keycloak:${KEYCLOAK_IMAGE_TAG}'
    command: ['start', '--optimized']
    environment:
      KC_DB_URL: 'jdbc:postgresql://keycloak-db:5432/${KEYCLOAK_DATABASE}'
      KC_DB_USERNAME: ${KEYCLOAK_DATABASE_USER}
      KC_HOSTNAME: 'https://${WEB_SERVER_OUTER_SOCKET}${KEYCLOAK_BASE_URL}'
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
      KC_HOSTNAME_STRICT: false
      # TODO (a.karmanov): Dynamic hostname (currently gives sporadic 401)
      # KC_PROXY_HEADERS: xforwarded
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_BASE_URL: '${KEYCLOAK_BASE_URL}'
    secrets:
      - keycloak_admin_password
      - keycloak_database_password
    depends_on:
      keycloak-db:
        condition: service_healthy

  keycloak-init:
    <<: *default
    restart: 'no'
    image: '${IMAGE_REGISTRY}/saltbox-keycloak-init:${KEYCLOAK_INIT_IMAGE_TAG}'
    environment:
      KEYCLOAK_ADMIN_EMAIL: '${SALTBOX_ADMIN_EMAIL}'
      KEYCLOAK_ADMIN_FIRSTNAME: '${SALTBOX_ADMIN_FIRSTNAME}'
      KEYCLOAK_ADMIN_LASTNAME: '${SALTBOX_ADMIN_LASTNAME}'
      KEYCLOAK_ADMIN_NAME: '${SALTBOX_ADMIN_USERNAME}'
      KEYCLOAK_CLIENT: '${KEYCLOAK_CLIENT}'
      KEYCLOAK_CLIENT_DIRECT_ACCESS: '${KEYCLOAK_CLIENT_DIRECT_ACCESS}'
      KEYCLOAK_REALM: '${KEYCLOAK_REALM}'
      KEYCLOAK_LOGIN_THEME: '${KEYCLOAK_LOGIN_THEME}'
      KEYCLOAK_URL: 'http://keycloak:8080${KEYCLOAK_BASE_URL}'
      KEYCLOAK_USER_EMAIL: '${SALTBOX_USER_EMAIL}'
      KEYCLOAK_USER_FIRSTNAME: '${SALTBOX_USER_FIRSTNAME}'
      KEYCLOAK_USER_LASTNAME: '${SALTBOX_USER_LASTNAME}'
      KEYCLOAK_USER_NAME: '${SALTBOX_USER_USERNAME}'
      KEYCLOAK_STRICT_ROLE_CHECK: '${KEYCLOAK_STRICT_ROLE_CHECK}'
      KEYCLOAK_INIT_LOG_LEVEL: '${KEYCLOAK_INIT_LOG_LEVEL:-info}'
    secrets:
      - keycloak_admin_password
      - keycloak_client_saltbox_core_password
      - saltbox_admin_password
      - saltbox_user_password

  salt-master:
    <<: *default
    profiles:
      - salt-master
    image: '${IMAGE_REGISTRY}/saltbox-bridge/salt-master:${SALT_MASTER_IMAGE_TAG}'
    environment:
      REDIS_USERNAME: '${REDIS_SALT_USERNAME}'
      REDIS_PASSWORD_FILE: '/run/secrets/redis_salt_password'
      SALT_MASTER_LOG_LEVEL: '${SALT_MASTER_LOG_LEVEL}'
      SALT_MINION_LOG_LEVEL: '${SALT_MINION_LOG_LEVEL}'
      SALTBOX_BRIDGE_LOG_LEVEL: '${SALTBOX_BRIDGE_LOG_LEVEL:-info}'
    secrets:
      - redis_salt_password
    ports:
      - '4505-4506:4505-4506'
    volumes:
      - '${SALT_MASTER_STORAGE_PATH}:/srv/salt_custom/'
      - '${SSHFS_STORAGE_PATH}:/srv/sshfs/'
      - 'redis_salt_certs:/etc/redis/certs/:ro'
      - 'salt_master_pki:/etc/salt/pki/'
      - 'salt_master_saltbox_var:/var/lib/saltbox-bridge/'
    depends_on:
      redis-salt:
        condition: service_healthy
        restart: false

  make-certs:
    <<: *default
    restart: 'on-failure'
    image: '${IMAGE_REGISTRY}/saltbox-compose/make-certs:${MAKE_CERTS_IMAGE_TAG}'
    environment:
      PROXY_CERT: '/mnt/proxy_certs/proxy.crt'
      SSL_ALT_NAMES_DNS: 'proxy,${WEB_SERVER_SSL_ALT_NAMES_DNS}'
      SSL_ALT_NAMES_IP: '${WEB_SERVER_SSL_ALT_NAMES_IP}'
      HIER_TEMPLATE: '/mnt/hier.yaml.jinja2'
      STATE_FILE: '/mnt/proxy_certs/.proxy_alt_names'
    entrypoint: '/docker/entrypoint.sh'
    volumes:
      - 'redis_salt_certs:/mnt/redis_certs/'
      - 'proxy_certs:/mnt/proxy_certs/'
      - './make-certs/hier.yaml.jinja2/:/mnt/hier.yaml.jinja2:ro'
    secrets:
      - redis_salt_ca_private_key_password
      - redis_salt_private_key_password

  redis-salt:
    <<: *default
    image: '${IMAGE_REGISTRY}/saltbox-compose/redis:${REDIS_IMAGE_TAG}'
    environment:
      REDIS_ENCRYPTION: 'on'
      TLS_AUTH_CLIENT: optional
      REDIS_USERNAME: '${REDIS_SALT_USERNAME}'
      REDIS_PASSWORD_SECRET_FILE: '/run/secrets/redis_salt_password'
      REDIS_PRIVATE_KEY_PASSWORD_SECRET: '/run/secrets/redis_salt_private_key_password'
    command:
      - --save 60 1
    healthcheck:
      test: >
        redis-cli --tls
        --user ${REDIS_SALT_USERNAME}
        --pass "$(cat "$$REDIS_PASSWORD_SECRET_FILE")"
        --cacert /etc/redis/certs/ca.crt ping
      start_period: '20s'
      start_interval: '2s'
      interval: '15s'
      retries: 3
    volumes:
      - 'redis_salt_data:/data/'
      - type: volume
        source: redis_salt_certs
        target: '/etc/redis/certs/'
        read_only: true
    expose:
      - 6379
    ports:
      - '${REDIS_SALT_EXPOSE_SOCKET}:6379'
    secrets:
      - redis_salt_password
      - redis_salt_private_key_password
    depends_on:
      make-certs:
        condition: service_completed_successfully

  redis-taskiq:
    <<: *default
    image: '${IMAGE_REGISTRY}/saltbox-compose/redis:${REDIS_IMAGE_TAG}'
    environment:
      REDIS_ENCRYPTION: 'off'
      REDIS_USERNAME: ${REDIS_TASKIQ_USERNAME}
      REDIS_PASSWORD_SECRET_FILE: '/run/secrets/redis_taskiq_password'
    command:
      - --save 60 1
    volumes:
      - 'redis_taskiq_data:/data/'
    expose:
      - 6379
    secrets:
      - redis_taskiq_password

  rabbitmq:
    <<: *default
    image: '${IMAGE_REGISTRY}/saltbox-compose/rabbitmq:${RABBITMQ_IMAGE_TAG}'
    environment:
      RABBITMQ_DEFAULT_USER: '${SALTBOX_ADMIN_USERNAME}'
      LOG_LEVEL: "${RABBITMQ_LOG_LEVEL:-info}"
    ports:
      - 5672:5672
    secrets:
      - rabbitmq_amqp_password
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]

  saltbox-gateway:
    <<: *default
    image: '${IMAGE_REGISTRY}/saltbox-gateway:${GATEWAY_IMAGE_TAG}'
    command: 'uvicorn'
    environment:
      LOG_LEVEL: '${GATEWAY_LOG_LEVEL}'
      SERVER_WS_SCHEME: 'wss'
      SERVER_OUTER_SOCKET: '${WEB_SERVER_OUTER_SOCKET}'
      REDIS_CA_CERT: '/etc/redis/certs/ca.crt'
      REDIS_URL: 'rediss://redis-salt:6379/0'
      REDIS_USERNAME: '${REDIS_SALT_USERNAME}'
      TIMEOUT_GRACEFUL_SHUTDOWN: '${GATEWAY_SHUTDOWN_TIMEOUT_SEC}'
      GATEWAY_HTTP_PORT: '${GATEWAY_HTTP_PORT}'
      UVICORN_WORKERS: '${GATEWAY_WORKERS:-1}'
      KEYCLOAK_FRONT_URL: 'https://${WEB_SERVER_OUTER_SOCKET}${KEYCLOAK_BASE_URL}'
      KEYCLOAK_SERVER_URL: 'http://keycloak:8080${KEYCLOAK_BASE_URL}'
      KEYCLOAK_REALM: '${KEYCLOAK_REALM}'
      KEYCLOAK_CLIENT: '${KEYCLOAK_CLIENT}'
      BASIC_AUTH_USERNAME: '${BASIC_AUTH_USERNAME:-}'
      BASIC_AUTH_PASSWORD: '${BASIC_AUTH_PASSWORD:-}'
      OPA_URL: 'http://opa:8181'
      RABBITMQ_ADMIN: '${SALTBOX_ADMIN_USERNAME}'
    volumes:
      - type: volume
        source: redis_salt_certs
        target: '/etc/redis/certs/'
        read_only: true
    secrets:
      - redis_salt_password
      - keycloak_client_saltbox_core_password
      - rabbitmq_amqp_password
    expose:
      - ${GATEWAY_HTTP_PORT}
    depends_on:
      redis-salt:
        condition: service_healthy
        restart: false

  saltbox-core: &core
    <<: *default
    image: '${IMAGE_REGISTRY}/saltbox-core:${CORE_IMAGE_TAG}'
    command: 'uvicorn'
    environment:
      BASE_URL_ROOT_PATH: '${BACKEND_PATH}'
      BASIC_AUTH_PASSWORD: '${BASIC_AUTH_PASSWORD:-}'
      BASIC_AUTH_USERNAME: '${BASIC_AUTH_USERNAME:-}'

      ALL_PROXY: '${SALTBOX_CORE_ALL_PROXY}'
      NO_PROXY: '${SALTBOX_CORE_NO_PROXY}'

      # Gateway environment variables
      DISCOVERY_DISCOVERY_URL: 'http://saltbox-gateway:${GATEWAY_HTTP_PORT}/api/discovery'
      DISCOVERY_FRONT_CONTAINER_NAME: '${CORE_FRONT_CONTAINER_NAME}'
      DISCOVERY_FRONT_CONTAINER_PORT: '${CORE_FRONT_CONTAINER_PORT}'
      DISCOVERY_INSTANCE_ID: '${CORE_INSTANCE_ID}'
      DISCOVERY_INSTANCE_HOST: '${CORE_HOST}'
      DISCOVERY_INSTANCE_PORT: '${CORE_PORT}'
      DISCOVERY_SERVER_OUTER_SOCKET: '${WEB_SERVER_OUTER_SOCKET}'
      DISCOVERY_SERVER_SCHEME: 'https'
      DISCOVERY_SERVER_WS_SCHEME: 'wss'
      DISCOVERY_SERVICE_DESCRIPTION: '${CORE_SERVICE_DESCRIPTION}'
      DISCOVERY_SERVICE_NAME: '${CORE_SERVICE_NAME}'
      DISCOVERY_SERVICE_TITLE: '${CORE_SERVICE_TITLE}'
      DISCOVERY_SERVICE_TYPE: '${CORE_SERVICE_TYPE}'
      DISCOVERY_SERVICE_VENDOR: '${CORE_SERVICE_VENDOR}'

      GITFS_USER: 'git'  # As in users.json of sshfs
      GITLAB_BASE_URL: '${GITLAB_BASE_URL}'
      GITLAB_GROUP_ID: '${GITLAB_GROUP_ID}'
      GITLAB_TOKEN: '${GITLAB_TOKEN}'

      IS_MODULE_INVENTORY_ON: '${SALTBOX_MODULE_INVENTORY_ON}'
      IS_MODULE_METRIC_ON: '${SALTBOX_MODULE_METRIC_ON}'

      KEYCLOAK_CLIENT: '${KEYCLOAK_CLIENT}'
      KEYCLOAK_FRONT_URL: 'https://${WEB_SERVER_OUTER_SOCKET}${KEYCLOAK_BASE_URL}'
      KEYCLOAK_REALM: '${KEYCLOAK_REALM}'
      KEYCLOAK_SERVER_URL: 'http://keycloak:8080${KEYCLOAK_BASE_URL}'

      RABBITMQ_ADMIN: '${SALTBOX_ADMIN_USERNAME}'
      RABBITMQ_AMQP_PASSWORD_FILE: '/run/secrets/rabbitmq_amqp_password'

      MONGO_HOST: '${MONGO_HOSTS}'
      MONGO_URI: '${MONGO_URI}'
      MONGO_DB: '${MONGO_DB}'
      MONGO_REPLICASET: '${MONGO_REPLICA_SET}'
      MONGO_USER: '${MONGO_USER}'
      MONGO_USER_PASSWORD_FILE: '/run/secrets/mongo_user_password'
      MONGO_EXPLAIN: '${MONGO_EXPLAIN}'

      OPA_URL: 'http://opa:8181'
      REDIS_CA_CERT: '/etc/redis/certs/ca.crt'
      REDIS_TASKIQ_DB: 0
      REDIS_TASKIQ_HOST: redis-taskiq
      REDIS_TASKIQ_PORT: 6379
      REDIS_TASKIQ_USERNAME: '${REDIS_TASKIQ_USERNAME}'
      REDIS_TASKIQ_USER_PASSWORD_FILE: '/run/secrets/redis_taskiq_password'
      REDIS_URL: 'rediss://redis-salt:6379/0'
      REDIS_USERNAME: '${REDIS_SALT_USERNAME}'
      REDIS_USER_PASSWORD_FILE: '/run/secrets/redis_salt_password'

      SALT_MODULES_PERMISSIONS: '{"user": "root", "group": "root", "file_mode": "0o644", "dir_mode": "0o755"}'
      SALT_MODULES_SERVE_DIR: '/mnt/salt/'

      SHOW_DOCS: '${SHOW_DOCS:-false}'
      SSHFS_PERMISSIONS: '{"user": "root", "group": "root", "file_mode": "0o644", "dir_mode": "0o755"}'
      SSHFS_USER: 'saltbox'  # As in users.json of sshfs

      TIMEOUT_GRACEFUL_SHUTDOWN: '${BACKEND_SHUTDOWN_TIMEOUT_SEC}'
      PILLARS_KEK_B64: '${PILLARS_KEK_B64}'
      LOG_LEVEL: '${SALTBOX_CORE_LOG_LEVEL}'
    volumes:
      - type: volume
        source: redis_salt_certs
        target: '/etc/redis/certs/'
        read_only: true
      - '/etc/hosts:/etc/hosts:ro'
      - 'saltbox_core_var:/var/lib/saltbox-core/'
      - 'salt_repos:/mnt/salt/'
      - '${SSHFS_STORAGE_PATH}:/srv/sshfs/'
      - '${LOCAL_CONFIG_BOXES_PATH}:/mnt/config-boxes/'
    secrets:
      - rabbitmq_amqp_password
      - redis_taskiq_password
      - redis_salt_password
      - mongo_user_password
      - keycloak_client_saltbox_core_password
    expose:
      - ${CORE_PORT}
    depends_on:
      saltbox-core-init:
        condition: service_completed_successfully
        restart: false

  saltbox-core-init:
    <<: *core
    restart: 'on-failure'
    command: 'shell saltbox-module-init'
    expose: []
    depends_on:
      redis-salt:
        condition: service_healthy
        restart: false

  saltbox-core-faststream-redis:
    <<: *core
    command: 'shell saltbox-faststream-redis'
    expose: []

  saltbox-core-faststream-rabbit:
    <<: *core
    command: 'shell saltbox-faststream-rabbit'
    expose: []

  saltbox-core-tasks-watcher:
    <<: *core
    command: 'shell saltbox-tasks-watcher'
    expose: []

  saltbox-core-jobs-watcher:
    <<: *core
    command: 'shell saltbox-jobs-watcher'
    expose: []

  saltbox-core-salt-buffer-manager:
    <<: *core
    command: 'shell saltbox-salt-buffer-manager'
    expose: []
    deploy:
      replicas: '${CORE_TASKIQ_WORKERS_COUNT:-1}'

  saltbox-core-taskiq-worker:
    <<: *core
    command: 'taskiq-worker'
    ports: []
    depends_on: *core-taskiq-depends

  saltbox-core-taskiq-salt-worker:
    <<: *core
    command: 'taskiq-salt-worker'
    ports: []
    depends_on: *core-taskiq-depends

  saltbox-core-taskiq-notify-worker:
    <<: *core
    command: 'taskiq-notify-worker'
    ports: []
    depends_on: *core-taskiq-depends

  saltbox-core-taskiq-scheduler:
    <<: *core
    command: 'taskiq-scheduler'
    ports: []
    depends_on: *core-taskiq-depends

  saltbox-frontend-root-config:
    <<: *default
    # TODO Delete FRONTEND_IMAGE_TAG fallback in few releases
    image: '${IMAGE_REGISTRY}/saltbox-frontend-root-config:${FRONTEND_ROOT_CONFIG_IMAGE_TAG:-${FRONTEND_IMAGE_TAG}}'
    expose:
      - ${FRONTEND_HTTP_PORT}

  saltbox-frontend-base:
    <<: *default
    # TODO Delete FRONTEND_IMAGE_TAG fallback in few releases
    image: '${IMAGE_REGISTRY}/saltbox-frontend-base:${BASE_FRONTEND_IMAGE_TAG:-${FRONTEND_IMAGE_TAG}}'
    expose:
      - ${FRONTEND_HTTP_PORT}

  saltbox-frontend-gateway:
    <<: *default
    # TODO Delete FRONTEND_IMAGE_TAG fallback in few releases
    image: '${IMAGE_REGISTRY}/saltbox-frontend-gateway:${GATEWAY_FRONTEND_IMAGE_TAG:-${FRONTEND_IMAGE_TAG}}'
    expose:
      - ${FRONTEND_HTTP_PORT}

  saltbox-frontend-core:
    <<: *default
    # TODO Delete FRONTEND_IMAGE_TAG fallback in few releases
    image: '${IMAGE_REGISTRY}/saltbox-frontend-core:${CORE_FRONTEND_IMAGE_TAG:-${FRONTEND_IMAGE_TAG}}'
    ports:
      - 8003:80
    expose:
      - ${FRONTEND_HTTP_PORT}

  mongo:
    <<: *mongo-default
    profiles:
      - mongo
    command: ['--quiet', '--wiredTigerCacheSizeGB', '${MONGO_CACHE_SIZE_GB}']
    hostname: '${MONGO_HOSTNAME}'  #NOTE: Important for replica set
    environment:
      MONGO_ROOT_USERNAME: root
      MONGO_ROOT_PASSWORD_FILE: '/run/secrets/mongo_root_password'
      MONGO_USER_USERNAME: '${MONGO_USER}'
      MONGO_USER_PASSWORD_FILE: '/run/secrets/mongo_user_password'
      MONGO_USER_DB: '${MONGO_DB}'
      MONGO_MIGRATION_USERNAME: '${MIGRATION_MONGO_USER}'
      MONGO_MIGRATION_DB: '${MIGRATION_MONGO_DB}'
      MONGO_MIGRATION_PASSWORD_FILE: '/run/secrets/migration_mongo_user_password'
      MONGOD_REPLICA_SET: '${MONGO_REPLICA_SET}'
      MONGO_EXPORTER_USERNAME: '${MONGO_EXPORTER}'
      MONGO_EXPORTER_PASSWORD_FILE: '/run/secrets/mongo_exporter_password'
      MONGOD_KEY_FILE: '/run/secrets/mongo_key_file'
    ports:
      - '${MONGO_EXPOSE_SOCKET}:27017'
    secrets:
      - mongo_key_file
      - mongo_root_password
      - mongo_user_password
      - mongo_exporter_password
      - migration_mongo_user_password
    volumes:
      - mongo_data:/var/lib/mongo/

  opa:
    <<: *default
    image: '${IMAGE_REGISTRY}/saltbox-compose/opa:${OPA_IMAGE_TAG}'
    command:
      - 'run'
      - '--server'
      - '--addr=0.0.0.0:8181'
      - '--watch'
      - '--log-format=json-pretty'
      - '--log-level=${OPA_LOG_LEVEL:-info}'
      - '--set=decision_logs.console=false'
      - '/policies/'
    ports:
      - '8181:8181'

  sshfs:
    <<: *default
    image: '${IMAGE_REGISTRY}/saltbox-compose/sshfs:${SSHFS_IMAGE_TAG}'
    environment:
      SSHFS_USER: '${SSHFS_USER}'
      USERS_FILE: '/mnt/sshfs_users.json'
      AUTHORIZED_KEYS_URL: 'http://saltbox-core:${CORE_PORT}/system/$${user}/authorized_keys'
    secrets:
      - sshfs_user_saltbox_password
      - sshfs_user_master_password
      - sshfs_user_migrator_password
    ports:
      - '${SSHFS_EXPOSE_SOCKET:-1022}:1022'
    volumes:
      - '${SSHFS_STORAGE_PATH}:/srv/sshfs/'
      - '${SSHFS_MIGRATION_PATH}:/srv/migrator/'
      - 'salt_repos:/srv/master/salt/'
      - '${SALT_MASTER_STORAGE_PATH}:/srv/master/salt_custom/'
      - './sshfs_conf/users.json:/mnt/sshfs_users.json:ro'
      - 'sshfs_host_keys:/etc/openssh-keys/'

configs: {}

volumes:
  keycloak-db_data: {}
  mongo_data: {}
  proxy_certs: {}
  redis_salt_certs: {}
  redis_salt_data: {}
  redis_taskiq_certs: {}
  redis_taskiq_data: {}
  salt_master_pki: {}
  salt_master_saltbox_var: {}
  salt_repos: {}
  saltbox_core_var: {}
  sshfs_host_keys: {}

secrets:
  migration_mongo_user_password:
    file: secrets/migration_mongo_user_password
  keycloak_admin_password:
    file: secrets/keycloak_admin_password
  keycloak_client_saltbox_core_password:  # Not private: exposed in /env.json
    file: secrets/keycloak_client_saltbox_core_password
  keycloak_database_password:
    file: secrets/keycloak_database_password
  mongo_root_password:
    file: secrets/mongo_root_password
  mongo_user_password:
    file: secrets/mongo_user_password
  mongo_exporter_password:
    file: secrets/mongo_exporter_password
  mongo_key_file:
    file: secrets/mongo_key_file
  redis_salt_ca_private_key_password:
    file: secrets/redis_salt_ca_private_key_password
  redis_salt_password:
    file: secrets/redis_salt_password
  redis_salt_private_key_password:
    file: secrets/redis_salt_private_key_password
  redis_taskiq_password:
    file: secrets/redis_taskiq_password
  rabbitmq_amqp_password:
    file: secrets/rabbitmq_amqp_password
  saltbox_admin_password:
    file: secrets/saltbox_admin_password
  saltbox_user_password:
    file: secrets/saltbox_user_password
  sshfs_user_master_password:
    file: secrets/sshfs_user_master_password
  sshfs_user_saltbox_password:
    file: secrets/sshfs_user_saltbox_password
  sshfs_user_migrator_password:
    file: secrets/sshfs_user_migrator_password
