---

## Salt.Box Compose backend override file for dev-mode

x-core-service: &core
    pull_policy: never
    environment:
      - DISCOVERY_LOG_LEVEL=DEBUG
    tty: true  # colorize logs
    image: '${LOCAL_IMAGE_NAMESPACE}/saltbox-core:dev'
    volumes:
      - '${CORE_BUILD_DIR}:/mnt/saltbox-core'
      - '${BRIDGE_MESSAGES_DIR}:/mnt/saltbox-bridge-messages:ro'
      - '${SDK_DIR}:/mnt/saltbox-sdk'
    tmpfs:
      - '/mnt/saltbox-bridge-messages/build/'
      - '/mnt/saltbox-bridge-messages/saltbox_bridge_messages.egg-info/'
      - '/mnt/saltbox-sdk/build/'
      - '/mnt/saltbox-sdk/saltbox_sdk.egg-info/'


services:
  keycloak-init:
    environment:
      KEYCLOAK_CLIENT_DIRECT_ACCESS: 'true'

  saltbox-gateway:
    build:
      context: $GATEWAY_BUILD_DIR
      target: dev
    environment:
      - LOG_LEVEL=DEBUG
    tty: true  # colorize logs
    image: '${LOCAL_IMAGE_NAMESPACE}/saltbox-gateway:dev'
    volumes:
      - '${GATEWAY_BUILD_DIR}:/mnt/saltbox-gateway:ro'
      - '${SDK_DIR}:/mnt/saltbox-sdk:ro'
    tmpfs:
      - '/mnt/saltbox-sdk/build/'
      - '/mnt/saltbox-sdk/saltbox_sdk.egg-info/'
      - '/mnt/saltbox-gateway/saltbox_gateway.egg-info/'

  saltbox-core:
    <<: *core
    build:
      context: $CORE_BUILD_DIR
      target: dev

  saltbox-core-init:
    <<: *core

  saltbox-core-faststream-redis:
    <<: *core

  saltbox-core-faststream-rabbit:
    <<: *core

  saltbox-core-tasks-watcher:
    <<: *core

  saltbox-core-jobs-watcher:
    <<: *core

  saltbox-core-salt-buffer-manager:
    <<: *core

  saltbox-core-taskiq-worker:
    <<: *core

  saltbox-core-taskiq-scheduler:
    <<: *core

  rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672

  opa:
    image: openpolicyagent/opa:latest-istio-static
    volumes:
      - './opa/policies:/policies'
