---
### Salt.Box Compose file for extracting system metrics

# Local generic does not override original
x-default-service: &default
  restart: 'on-failure'
  stop_grace_period: ${STOP_GRACE_PERIOD}

services:
  proxy:
    volumes:
      - ./proxy/includes/metrics.enabled.conf.template:/etc/nginx/includes/10-metrics.conf.template:ro

  keycloak-init:
    environment:
      KEYCLOAK_CLIENT_GRAFANA: '${KEYCLOAK_CLIENT_GRAFANA}'
    secrets:
      - keycloak_client_grafana_password

  grafana:
    <<: *default
    image: grafana/grafana:12.0.2-security-01 #TODO: add to registry
    environment:
      GF_SERVER_PROTOCOL: 'http'
      GF_SERVER_SERVE_FROM_SUB_PATH: true
      GF_SERVER_DOMAIN: '${WEB_SERVER_OUTER_SOCKET}'
      GF_SERVER_ROOT_URL: 'https://${WEB_SERVER_OUTER_SOCKET}/grafana/'
      GF_AUTH_ANONYMOUS_ENABLED: false
      GF_AUTH_BASIC_ENABLED: false
      GF_AUTH_DISABLE_LOGIN_FORM:  true
      GF_AUTH_GENERIC_OAUTH_ENABLED: true
      GF_AUTH_GENERIC_OAUTH_AUTO_LOGIN: true
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: true
      GF_AUTH_GENERIC_OAUTH_ALLOW_ASSIGN_GRAFANA_ADMIN: true
      GF_AUTH_GENERIC_OAUTH_USE_TOKEN_INFO_ENDPOIT: false
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: '${KEYCLOAK_CLIENT_GRAFANA}'
      GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH: 'full_name'
      GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH: 'username'
      GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_PATH: 'email'
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET__FILE: '/run/secrets/keycloak_client_grafana_password'
      GF_AUTH_GENERIC_OAUTH_SCOPES: 'openid email profile offline_access roles'
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: 'https://${WEB_SERVER_OUTER_SOCKET}${KEYCLOAK_BASE_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/auth'
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: 'http://keycloak:8080${KEYCLOAK_BASE_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token'
      GF_AUTH_GENERIC_OAUTH_API_URL: 'http://keycloak:8080${KEYCLOAK_BASE_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/userinfo'
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(resource_access.grafana.roles, 'grafana_admin') && 'Admin' || 'Viewer'"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: '/etc/grafana/provisioning/dashboards/dashboard.json'
      GF_LOG_LEVEL: '${BACKEND_LOG_LEVEL}'
    secrets:
      - keycloak_client_grafana_password
    ports:
      - '3000:3000'
    volumes:
      - './metrics/grafana/dashboards/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json'
      - './metrics/grafana/dashboards/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro'
      - './metrics/grafana/datasources/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro'
      - 'grafana_data:/var/lib/grafana'
    depends_on:
      grafana-loki:
        condition: service_healthy
      promtail:
        condition: service_healthy
      prometheus:
        condition: service_started

  grafana-loki:
    <<: *default
    image: grafana/loki:3.4.5 #TODO: add to registry
    environment:
      TZ: '${GRAFANA_SYSTEM_TIMEZONE}'
    expose:
      - '3100'
    volumes:
      - './metrics/grafana/datasources/grafana-loki.yaml:/etc/loki/config.yaml:ro'
      - 'grafana_loki_config:/etc/loki'
    healthcheck:
      test: wget --quiet --tries=1 --output-document=- http://localhost:3100/ready | grep -q -w ready || exit 1
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  promtail:
    <<: *default
    image: grafana/promtail:3.4.5 #TODO: add to registry
    command:
      - '-config.expand-env=true'
      - '-config.file=/etc/promtail/config.yaml'
    expose:
      - '9080'
    volumes:
      - '/var/lib/docker/containers:/var/lib/docker/containers:ro'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './metrics/promtail.yaml:/etc/promtail/config.yaml:ro'
      - 'promtail_data:/etc/promtail'
    healthcheck:
          test: ["CMD-SHELL", "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/9080; exit $?;'"]
          start_period: 10s
          interval: 10s
          timeout: 5s
          retries: 3

  prometheus:
      <<: *default
      image: prom/prometheus:v3.5.0 #TODO: add to registry
      command:
        - '--web.external-url=https://${WEB_SERVER_OUTER_SOCKET}/prometheus/'
        - '--web.route-prefix=/prometheus/'
        - '--config.file=/etc/prometheus/prometheus.yml'
      ports:
        - '9090:9090'
      volumes:
        - './metrics/prometheus.yml:/etc/prometheus/prometheus.yml:ro'
        - 'prometheus_data:/data/prometheus'

volumes:
  grafana_data: {}
  grafana_loki_config: {}
  promtail_data: {}
  prometheus_data: {}

secrets:
  keycloak_client_grafana_password:
    file: secrets/keycloak_client_grafana_password
