services:
  proxy:
    build:
      context: nginx-proxy/
    container_name: proxy
    develop:
      watch:
        - action: rebuild
          path: nginx-proxy/
    env_file:
      - .env
    ports:
      - '80:80'
    depends_on:
      - fastms-core
      - fastms-frontend
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: fastms-keycloak
    command: start --optimized
    env_file:
      - .env
    environment:
      KC_HOSTNAME: 'http://${KEYCLOACK_HOST}${KEYKOACK_BASE_URL}'
      KC_LOG_LEVEL: info
      KC_HTTP_ENABLED: true
      HTTP_ADDRESS_FORWARDING: true
    expose:
        - 8080

  salt-master:
    build:
      context: salt/
      target: salt-master
    image: fastms-salt-master
    init: true
    container_name: fastms-salt-master
    develop:
      watch:
        - action: rebuild
          path: salt/
    ports:
      - '4505-4506:4505-4506'
    volumes:
      - 'salt_master_pki:/etc/salt/pki/'
    depends_on:
      - redis-salt

  redis-salt:
    image: redis:7.2-alpine
    container_name: fastms-redis-salt
    command:
      - --save 60 1
    volumes:
      - 'redis_salt_data:/data/'

  fastms-core:
    build:
      context: fastms-core/
    container_name: fastms-core
    develop:
      watch:
        - action: rebuild
          path: fastms-core/
    env_file:
      - .env
    environment:
      SALT_URL: 'https://fastms-salt-master:8000'
      REDIS_URL: 'redis://fastms-redis-salt:6379/0'
      ROOT_PATH: '/api/core'
    expose:
      - ${BACKEND_HTTP_PORT}
    restart: no
    depends_on:
      - mongo

  fastms-frontend:
    build:
      context: fastms-frontend/
      args:
        VITE_API_URL_HTTP: 'http://${SERVER_NAME}${BACKEND_BASE_URL}'
        VITE_API_URL_WS: 'ws://${SERVER_NAME}${BACKEND_BASE_URL}'
    container_name: fastms-frontend
    develop:
      watch:
        - action: rebuild
          path: fastms-frontend/
    env_file:
      - .env
    expose:
      - ${FRONTEND_HTTP_PORT}

  mongo:
    image: mongo:7
    command: --quiet
    environment:
      # TODO Generate
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  salt_master_pki: {}
  redis_salt_data: {}
