x-default-service: &default
  restart: 'on-failure'
  stop_grace_period: ${STOP_GRACE_PERIOD}

services:
  sshfs_manager:
    <<: *default
    build:
      context: ./sshfs_manager
    image: sshfs_manager:${SSHFS_IMAGE_TAG}
    extra_hosts: [ "localhost:host-gateway" ]
    user: '0'
    environment:
      FILEBROWSER_CONFIG: "data/config.yaml"
      FILEBROWSER_DATABASE: "./database.db"
      WEB_SERVER_OUTER_SOCKET: "${WEB_SERVER_OUTER_SOCKET}"
      KEYCLOAK_REALM: "${KEYCLOAK_REALM}"
      KEYCLOAK_CLIENT: ${KEYCLOAK_CLIENT}
      KEYCLOAK_BASE_URL: "${KEYCLOAK_BASE_URL}"
    volumes:
      - './sshfs_manager/database.db:/home/filebrowser/database.db'
      - 'saltbox_salt_extmod:/srv/salt_extmod:ro'
      - 'saltbox_salt_local:/srv/salt_local'
      - 'saltbox_salt_master_local:/srv/salt_master_local'
      - 'saltbox_saltbox_salt:/srv/saltbox_salt'
      - '${SALT_MASTER_STORAGE_PATH}:/srv/salt'
      - '${SSHFS_STORAGE_PATH}:/srv/sshfs'
    secrets:
      - keycloak_client_saltbox_core_password
    depends_on:
      keycloak-init:
        condition: service_completed_successfully
        restart: false

  keycloak-init:
    environment:
      SSHFS_MANAGER_ENABLED: true

  proxy:
    volumes:
      - ./proxy/includes/sshfs-manager.enabled.conf:/etc/nginx/includes/sshfs-manager.conf:ro
