---

## FastMS Compose SaltStack override file for dev-mode.
#
# Local generic does not override original
x-default-service: &default
  restart: unless-stopped
  stop_grace_period: ${STOP_GRACE_PERIOD}

# FIXME Do not clean keys on restart
services:
  # Override
  salt-master:
    build:
      context: salt/
      target: salt-master
    image: 'salt-master:dev'
    develop:
      watch:
        - path: salt/
          action: rebuild
          ignore:
            - 'config/minion.yaml'
            - '**/*.md'
    ports:
      - '4505-4506:4505-4506'
      - '8001:8000'

  # Additional services
  clean-keys-cmd:
    <<: *default
    build:
      context: salt/
      target: salt-master
    image: 'salt-master:dev'
    restart: 'on-failure:3'
    command: 'salt-key --delete-all --yes'
    profiles:
      - salt-master
    volumes:
      - 'salt_master_pki:/etc/salt/pki/'
  salt-minion:
    <<: *default
    build:
      context: salt/
      target: salt-minion
    init: true
    develop:
      watch:
        - path: 'salt/config/minion.yaml'
          action: rebuild
        - path: 'salt/Dockerfile'
          action: rebuild
    deploy:
      mode: replicated
      replicas: ${SALT_MINION_REPLICAS:-1}
    profiles:
      - salt-master
    depends_on:
      clean-keys-cmd:
        condition: service_completed_successfully
        required: false
        restart: true
      salt-master:
        condition: service_started
        restart: false
