---

## salt.box compose backend override file for dev-mode.

x-redis-based: &redis
  build:
    context: redis/
  image: 'redis-salt-box:dev'

services:
  keycloak-init:
    environment:
      KEYCLOAK_CLIENT_DIRECT_ACCESS: 'true'
  salt-box-core: &core
    build:
      context: $CORE_BUILD_DIR
      target: dev
    environment:
      - DEBUG=True
    tty: true  # colorize logs
    image: 'salt-box-core:dev'
    volumes:
      - '${CORE_BUILD_DIR}:/mnt/salt_box_core'
  salt-box-core-salt-bridge-consumer:
    <<: *core
  salt-box-core-tasks-watcher:
    <<: *core
  salt-box-core-celery-beat:
    <<: *core
  salt-box-core-celery-worker-tasks:
    <<: *core
  redis-salt:
    <<: *redis
  redis-celery:
    <<: *redis
