# Local generic does not override original
x-default-service: &default
  restart: unless-stopped
  stop_grace_period: ${STOP_GRACE_PERIOD}
  env_file:
    - .env

services:
# Overrides
  salt-master:
    ports:
      - '4505-4506:4505-4506'
      - '8001:8000'
  redis-salt:
    ports:
      - '6379:6379'

  mongo:
    ports:
      - ${MONGO_PORT:-27017}:${MONGO_PORT:-27017}
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

# Additional services
  # FIXME Clean inside container with script
  clean-keys-cmd:
    pull_policy: never
    image: fastms-salt-master
    command: 'salt-key --delete-all --yes'
    depends_on:
      salt-master:
        restart: true
        condition: service_started
    volumes:
      - 'salt_master_pki:/etc/salt/pki/'
  salt-minion:
    <<: *default
    build:
      context: salt/
      target: salt-minion
    init: true
    develop:
      watch:
        - action: rebuild
          path: salt/
    deploy:
      mode: replicated
      replicas: ${SALT_MINION_REPLICAS:-1}
    depends_on:
      clean-keys-cmd:
        restart: true
        condition: service_completed_successfully

volumes:
  mongo_data: {}
  mongo_config: {}
