global:
  scrape_interval: 3s

scrape_configs:

  - job_name: "saltbox-bridge"
    metrics_path: /metrics
    static_configs:
      - targets: ["salt-master:8004"]

  - job_name: "saltbox-core"
    metrics_path: /metrics
    static_configs:
      - targets: ["saltbox-core:8000"]
