global:
  scrape_interval: 3s

scrape_configs:

  - job_name: "core"
    metrics_path: /metrics
    static_configs:
      - targets: ["saltbox-core:8000"]

  - job_name: "gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["saltbox-gateway:8001"]
    basic_auth:
      username: '' # depends on BASIC_AUTH_*
      password: ''

  - job_name: "opa"
    metrics_path: /metrics
    static_configs:
      - targets: ["opa:8181"]
