[project]
name = "saltbox-compose-scripts"
requires-python = ">=3.7.3"
dynamic = ["version"]
dependencies = []

[project.optional-dependencies]
dev = [
  "mypy",
  "python-lsp-server[all]",
  "ruff",
  "ipython",
]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["bin"]

[tool.flake8]
max-line-length = 120
extend-ignore = [ ]

[tool.ruff]
line-length = 120
target-version = "py37"

[tool.ruff.lint]
ignore = [
    "B019",
    "SIM108",  # Annoying ternary op suggestion
]

[tool.ruff.format]
quote-style = "single"

[tool.uv.build-backend]
module-name = "bin"
module-root = ""

[dependency-groups]
dev = [
    "pylsp-mypy>=0.6.7",
    "pylsp-rope>=0.1.17",
]
