location /sshfs/ {

    # Docker embedded DNS resolver with retries
    resolver 127.0.0.11 valid=10s ipv6=off status_zone dns_resolver;
    resolver_timeout 5s;

    # Force DNS resolution on each request to handle container restarts
    set $upstream_host "sshfs_manager";
    set $upstream_port "80";

    auth_request_set $user               $upstream_http_x_auth_request_user;
    auth_request_set $email              $upstream_http_x_auth_request_email;
    proxy_set_header X-User              $user;
    proxy_set_header X-Email             $email;

    proxy_set_header Host                $host;
    proxy_set_header X-Forwarded-Host    $host;
    proxy_set_header X-Forwarded-Proto   $scheme;
    proxy_set_header X-Forwarded-For     $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP           $remote_addr;
    proxy_set_header X-Forwarded-Prefix  /sshfs/;

    proxy_pass http://$upstream_host:$upstream_port;
}
