{
 "title": "🧂Salt.Box",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Count of events",
   "type": "stat",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "event_payload_size_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total message size",
   "type": "stat",
   "gridPos": { "h": 16, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "event_payload_size_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Task status",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "task_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tagged event total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "event_total_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tagged event size",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "event_total_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Count of job",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "job_new_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Job duration",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "job_ret", "legendFormat": "__auto" }
   ]
  }
 ]
}