bind_ip = 127.0.0.1
port = 27017
fork = false
#pidfilepath = /run/mongo/mongod.pid
#logpath = /var/log/mongo/mongod.log
dbpath =/var/lib/mongo

# Turn on/off security.  Off is currently the default
#noauth = true
#auth = true

# Turns off server-side scripting.  This will result in greatly limited
# functionality
#noscripting = true

# Replication Options

# in replicated mongo databases, specify here whether this is a slave or master
#slave = true
#source = master.example.com
# Slave only: specify a single database to replicate
#only = master.example.com
# or
#master = true
#source = slave.example.com

# Address of a server to pair with.
#pairwith = <server:port>
# Address of arbiter server.
#arbiter = <server:port>
# Automatically resync if slave data is stale
#autoresync
# Custom size for replication operation log.
#oplogSize = <MB>
# Size limit for in-memory storage of op ids.
#opIdMem = <bytes>
