user: salt
module_dirs:
  - /srv/salt_extmod/
auto_accept: true
engines:
  - redis_bridge:
      host: fastms-redis-salt
      # Time to live for job returns and grains (sec)
      expire: 604800
schedule:
  redis_bridge_cleanup:
    hours: 3
    function: redis_bridge.cleanup_expired_jobs
    kwargs:
      # Age of jobs to delete (sec)
      expire: 604800
      host: fastms-redis-salt

# vi: syn=yaml
