[supervisord]
user=root
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[eventlistener:quit_on_failure]
# Exit if one of processes will fail
events=PROCESS_STATE_FATAL
command=sh -c 'while true; do echo "READY"; read line; kill -15 1; echo "RESULT 2"; echo "OK"; done'

[program:prepare-configs]
command=/usr/local/bin/prepare_onfigs.sh
autorestart=unexpected
startsecs=0
priority=0

[program:salt-master]
command=/usr/local/bin/salt-master -l '%(ENV_LOG_LEVEL)s'
environment=LOG_LEVEL='%(ENV_SALT_MASTER_LOG_LEVEL)s'
priority=10
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:salt-api]
command=/usr/local/bin/salt-api -l '%(ENV_LOG_LEVEL)s'
environment=LOG_LEVEL='%(ENV_SALT_API_LOG_LEVEL)s'
priority=20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

# vi: syn=dosini
