{
 "title": "🧂Salt.Box",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Count of Events",
   "type": "stat",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "event_payload_size_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Size of Event Messages",
   "type": "stat",
   "gridPos": { "h": 16, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "event_payload_size_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Task Execution Status",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "task_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tagged Event Total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "event_total_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tagged Event Size",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "event_total_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Count of Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "job_new_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Last Job Duration",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "job_ret", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum / http_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_request_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Requests Count",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_request_endpoint_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total HTTP Errors",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "targets": [
    { "expr": "http_error_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Percent of 2xx HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(endpoint) (http_request_endpoint_count{status_code=~\"2.*\"}) / sum by(endpoint) (http_request_endpoint_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_request_endpoint_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percent of 5xx HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(endpoint) (http_request_endpoint_count{status_code=~\"5.*\"}) / sum by(endpoint) (http_request_endpoint_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SaltBox Core Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"core\"}"
    }
   ]
  },
  {
   "title": "SaltBox Gateway Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"gateway\"} |= ``"
    }
   ]
  }
 ]
}