---

fileserver_backend:
  - roots
  - gitfs
gitfs_remotes:
  - 'https://dev.saltbox.pro/a.baikov/test-public-sls-repo.git'
  - 'https://dev.saltbox.pro/salt.box/salt-box-migration-sls':
    - user: salt-box-migration-sls
    - password: 'glpat-xxRXtXaBiVzWfvj4pYwZ'

# vi: ft=yaml
