user: salt
module_dirs:
  - /srv/salt_extmod/
engines:
  - redis_bridge:
      host: fastms-redis-salt
      # Time to live for job returns (sec)
      expire: 604800
auto_accept: true

# vi: syn=yaml
