global:
  scrape_interval: 3s

scrape_configs:

  - job_name: "saltbox-metric"
    metrics_path: /metrics
    static_configs:
      - targets: ["saltbox-metric:8004"]

  - job_name: "saltbox-core"
    metrics_path: /metrics
    static_configs:
      - targets: ["saltbox-core:8000"]

  - job_name: "saltbox-gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["saltbox-gateway:8001"]
